<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { CameraStatus, CreateCameraRequest, RuntimeStatus } from '../types/iris'

const props = defineProps<{ status: RuntimeStatus }>()
const api = window.api
type CameraDraft = { camera_id: number; device_index: number | null; device_symbolic_link: string; width: number; height: number; frame_rate: number; format: string; cuda_device: number; sample_queue_capacity: number; frame_pool_capacity: number; overflow: string; rotation: string; allow_format_fallback: boolean; reconnect: boolean }
const blank = (): CameraDraft => ({ camera_id: 1, device_index: 0, device_symbolic_link: '', width: 1920, height: 1080, frame_rate: 30, format: 'mjpeg', cuda_device: 0, sample_queue_capacity: 1, frame_pool_capacity: 4, overflow: 'drop-oldest', rotation: 'none', allow_format_fallback: false, reconnect: true })
const editingId = ref<number | null>(null), draft = ref<CameraDraft>(blank()), saved = ref<CameraDraft>(blank()), mode = ref<'closed' | 'add' | 'edit'>('closed'), busy = ref(false), error = ref(''), notice = ref('')
const cameras = computed(() => props.status.cameras || [])
const dirty = computed(() => JSON.stringify(draft.value) !== JSON.stringify(saved.value))
const connectedCount = computed(() => cameras.value.filter((camera) => camera.connected || camera.state === 'connected').length)
const errorCount = computed(() => cameras.value.filter((camera) => Boolean(camera.last_error) || (camera.source_errors ?? 0) > 0).length)
function numberRate(camera: CameraStatus): number { return typeof camera.frame_rate === 'number' ? camera.frame_rate : camera.frame_rate?.value ?? camera.fps }
function cameraError(camera: CameraStatus): string { return camera.last_error || (camera.source_errors ? `${camera.source_errors} capture source error${camera.source_errors === 1 ? '' : 's'}` : '') }
function fromCamera(camera: CameraStatus): CameraDraft { return { camera_id: camera.camera_id, device_index: camera.device_index ?? 0, device_symbolic_link: camera.device_symbolic_link ?? '', width: camera.width, height: camera.height, frame_rate: numberRate(camera), format: camera.format ?? 'mjpeg', cuda_device: camera.cuda_device ?? 0, sample_queue_capacity: camera.sample_queue_capacity ?? 1, frame_pool_capacity: camera.frame_pool_capacity ?? 4, overflow: camera.overflow ?? 'drop-oldest', rotation: camera.rotation ?? 'none', allow_format_fallback: camera.allow_format_fallback ?? false, reconnect: camera.reconnect ?? true } }
function openAdd(): void { mode.value = 'add'; editingId.value = null; draft.value = blank(); saved.value = blank(); error.value = ''; notice.value = '' }
function openEdit(camera: CameraStatus): void { if (dirty.value && !window.confirm('Discard unsaved camera changes?')) return; mode.value = 'edit'; editingId.value = camera.camera_id; draft.value = fromCamera(camera); saved.value = fromCamera(camera); error.value = ''; notice.value = '' }
function cancel(): void { mode.value = 'closed'; error.value = ''; notice.value = '' }
function validate(): string | null { if (!Number.isInteger(draft.value.camera_id) || draft.value.camera_id < 0) return 'Camera ID must be a non-negative integer.'; if (mode.value === 'add' && cameras.value.some((camera) => camera.camera_id === draft.value.camera_id)) return `Camera ID ${draft.value.camera_id} is already configured.`; if (draft.value.device_index === null && !draft.value.device_symbolic_link.trim()) return 'Choose a device index or symbolic link.'; if (draft.value.device_index !== null && draft.value.device_index < 0) return 'Device index must be zero or greater.'; if (draft.value.width < 1 || draft.value.height < 1) return 'Width and height must be positive.'; if (draft.value.frame_rate <= 0) return 'Frame rate must be greater than 0 FPS.'; if (draft.value.cuda_device < 0) return 'CUDA device must be zero or greater.'; if (draft.value.sample_queue_capacity < 1 || draft.value.frame_pool_capacity < 1) return 'Queue capacities must be positive.'; return null }
function body(): Omit<CreateCameraRequest, 'camera_id'> { const { camera_id: _id, ...value } = draft.value; return value }
async function submit(): Promise<void> { const validation = validate(); if (validation) { error.value = validation; return }; busy.value = true; error.value = ''; notice.value = mode.value === 'add' ? 'Creating camera…' : 'Saving camera…'; try { if (mode.value === 'add') { await api.addCamera({ camera_id: draft.value.camera_id, ...body() }); editingId.value = draft.value.camera_id } else if (editingId.value !== null) await api.configureCamera(editingId.value, body()); saved.value = { ...draft.value }; mode.value = 'edit'; notice.value = 'Camera applied'; } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause); notice.value = '' } finally { busy.value = false } }
async function remove(camera: CameraStatus): Promise<void> { if (!window.confirm(`Remove Camera ${camera.camera_id}? This will stop capture for this camera and remove its configuration.`)) return; busy.value = true; error.value = ''; notice.value = 'Removing camera…'; try { await api.removeCamera(camera.camera_id); if (editingId.value === camera.camera_id) cancel(); notice.value = 'Camera removed' } catch (cause) { error.value = cause instanceof Error ? cause.message : String(cause); notice.value = '' } finally { busy.value = false } }
watch(() => props.status.cameras, (list) => { if (editingId.value !== null) { const current = list?.find((camera) => camera.camera_id === editingId.value); if (current && !dirty.value) { draft.value = fromCamera(current); saved.value = fromCamera(current) } } })
</script>
<template>
  <section class="camera-manager" aria-label="Camera manager">
    <header class="camera-manager-head"><div><strong>CAMERAS</strong><small>{{ cameras.length }} configured · {{ connectedCount }} connected<span v-if="errorCount"> · {{ errorCount }} error{{ errorCount === 1 ? '' : 's' }}</span></small></div><button class="primary-action" :disabled="busy" @click="openAdd">+ ADD CAMERA</button></header>
    <div v-if="!cameras.length" class="camera-empty">No cameras configured yet. Add a capture source to begin.</div>
    <article v-for="camera in cameras" :key="camera.camera_id" class="camera-card"><div class="camera-card-main"><span :class="['camera-status-dot', camera.connected || camera.state === 'connected' ? 'connected' : cameraError(camera) ? 'error' : 'idle']"></span><div><strong>CAMERA {{ String(camera.camera_id).padStart(2, '0') }}</strong><small>{{ camera.device_symbolic_link || `Device ${camera.device_index ?? '—'}` }}</small><small>{{ camera.width }} × {{ camera.height }} · {{ numberRate(camera) }} FPS · {{ camera.format || 'unknown' }}</small><small v-if="cameraError(camera)" class="camera-error">{{ cameraError(camera) }}</small></div></div><div class="camera-card-actions"><button :disabled="busy" @click="openEdit(camera)">EDIT</button><button class="danger-action" :disabled="busy" @click="remove(camera)">REMOVE</button></div></article>
    <form v-if="mode !== 'closed'" class="camera-editor" @submit.prevent="submit"><header><div><strong>{{ mode === 'add' ? 'ADD CAMERA' : `EDIT CAMERA ${editingId}` }}</strong><small v-if="dirty" class="unsaved">Unsaved changes</small></div><button type="button" :disabled="busy" @click="cancel">CANCEL</button></header><fieldset :disabled="busy"><legend>Identity</legend><label>Camera ID<input v-model.number="draft.camera_id" type="number" min="0" /></label><label>Connection method<select v-model="draft.device_index"><option :value="0">Device index</option><option :value="null">Symbolic link</option></select></label><label v-if="draft.device_index !== null">Device index<input v-model.number="draft.device_index" type="number" min="0" /></label><label v-else>Symbolic link<input v-model="draft.device_symbolic_link" placeholder="\\\\?\\usb#..." /></label></fieldset><fieldset :disabled="busy"><legend>Capture</legend><div class="camera-field-row"><label>Width (px)<input v-model.number="draft.width" type="number" min="1" /></label><label>Height (px)<input v-model.number="draft.height" type="number" min="1" /></label></div><div class="camera-field-row"><label>Frame rate (FPS)<input v-model.number="draft.frame_rate" type="number" min="1" step="0.1" /></label><label>Format<select v-model="draft.format"><option>mjpeg</option><option>yuy2</option><option>bgra8</option></select></label></div><label>Rotation<select v-model="draft.rotation"><option>none</option><option>cw90</option><option>180</option><option>ccw90</option></select></label><label><input v-model="draft.allow_format_fallback" type="checkbox" /> Allow format fallback</label></fieldset><details><summary>Advanced performance</summary><fieldset :disabled="busy"><div class="camera-field-row"><label>CUDA device<input v-model.number="draft.cuda_device" type="number" min="0" /></label><label>Sample queue<input v-model.number="draft.sample_queue_capacity" type="number" min="1" /></label></div><div class="camera-field-row"><label>Frame pool<input v-model.number="draft.frame_pool_capacity" type="number" min="1" /></label><label>Overflow<select v-model="draft.overflow"><option>block</option><option>drop-oldest</option><option>drop-newest</option></select></label></div><label><input v-model="draft.reconnect" type="checkbox" /> Reconnect automatically</label></fieldset></details><p v-if="error" class="camera-form-error" role="alert">{{ error }}</p><p v-if="notice" class="camera-form-notice" role="status">{{ notice }}</p><button class="primary-action" type="submit" :disabled="busy || (mode === 'edit' && !dirty)">{{ busy ? notice : mode === 'add' ? 'CREATE CAMERA' : 'APPLY CHANGES' }}</button></form>
  </section>
</template>
