<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import type { CameraStatus, RuntimeStatus } from '../types/iris'
const props = defineProps<{ status: RuntimeStatus }>()
const playing = ref(true), fatalError = ref(''), failed = ref(new Set<number>()), fps = ref(new Map<number, number>())
const cameras = computed<CameraStatus[]>(() => props.status.cameras ?? []), port = computed(() => props.status.preview?.port || 8080)
const canvases = new Map<number, HTMLCanvasElement>(), decoders = new Map<number, VideoDecoder>(); let socket: WebSocket|undefined, timer: number|undefined, generation = 0, last = new Map<number, number>(), awaitingKeyframe = new Set<number>()
function setCanvas(id:number, value:unknown):void { if(value instanceof HTMLCanvasElement) canvases.set(id,value); else canvases.delete(id) }
function disposeDecoder(id:number, decoder:VideoDecoder):void { if(decoders.get(id)!==decoder)return; decoders.delete(id); if(decoder.state!=='closed')try{decoder.close()}catch{} }
function closeDecoders():void { for(const [id,decoder] of decoders)disposeDecoder(id,decoder); awaitingKeyframe.clear() }
function retry():void { if(timer) return; timer=window.setTimeout(()=>{timer=undefined;connect()},1000) }
function connect():void {
  if(!playing.value || !cameras.value.length) return; const current=++generation; socket?.close(); closeDecoders(); fatalError.value=''
  const ws=new WebSocket(`ws://127.0.0.1:${port.value}/api/preview/stream`); ws.binaryType='arraybuffer'; socket=ws
  ws.onopen=()=>{console.info('[preview] websocket open');ws.send(JSON.stringify({version:1,type:'hello',cameras:cameras.value.map(camera=>camera.camera_id)}))}
  ws.onmessage=(event)=>{
    if(current!==generation) return
    if(typeof event.data==='string') { try { const message=JSON.parse(event.data) as {type:string;message?:string;streams?:Array<{camera_id:number;width?:number;height?:number;codec?:string;description?:string}>}; console.info('[preview] message',message.type,message); if(message.type==='error'){fatalError.value=message.message||'Preview connection failed';retry();return}; if(message.type==='config') for(const stream of message.streams||[]){const canvas=canvases.get(stream.camera_id), context=canvas?.getContext('2d'); if(!canvas||!context||!('VideoDecoder' in window)) throw new Error('WebCodecs VideoDecoder is unavailable'); const id=stream.camera_id; const codec=stream.codec||'avc1.42E01E'; const decoder=new VideoDecoder({output:(frame)=>{context.drawImage(frame,0,0,canvas.width,canvas.height);frame.close();last.set(id,performance.now())},error:(error)=>{console.error('[preview] decoder error',id,error);if(current===generation&&decoders.get(id)===decoder){failed.value=new Set(failed.value).add(id);disposeDecoder(id,decoder);retry()}}}); console.info('[preview] configuring decoder',id,codec,stream.width,stream.height); decoder.configure({codec,description:stream.description?Uint8Array.from(atob(stream.description),c=>c.charCodeAt(0)):undefined}); decoders.set(id,decoder)} } catch(error) { console.error('[preview] message/configuration error',error); fatalError.value='Preview decoder configuration failed'; retry() } return }
    const data=new Uint8Array(event.data as ArrayBuffer); if(data.length<32||String.fromCharCode(...data.slice(0,4))!=='IRWS') return; const view=new DataView(data.buffer,data.byteOffset,data.byteLength), camera=view.getUint32(8,true), timestamp=Number(view.getBigUint64(20,true)), flags=view.getUint16(6,true), length=view.getUint32(28,true), decoder=decoders.get(camera); if(!decoder||length+32>data.length||!playing.value)return; if(flags&2){awaitingKeyframe.add(camera);if(!(flags&1))return} if(awaitingKeyframe.has(camera)&&!(flags&1))return; if(flags&1)awaitingKeyframe.delete(camera); if(decoders.get(camera)!==decoder||decoder.state==='closed')return; try{decoder.decode(new EncodedVideoChunk({type:(flags&1)?'key':'delta',timestamp,data:data.slice(32,32+length)}))}catch{if(current===generation&&decoders.get(camera)===decoder){disposeDecoder(camera,decoder);awaitingKeyframe.add(camera);retry()}}
  }
  ws.onerror=()=>{console.error('[preview] websocket error');fatalError.value='Preview WebSocket unavailable';retry()}; ws.onclose=()=>{console.warn('[preview] websocket closed');if(current===generation)retry()}
}
function toggle():void { playing.value=!playing.value; if(playing.value)connect() }
onMounted(()=>{connect();window.setInterval(()=>{const now=performance.now(),next=new Map<number,number>();for(const camera of cameras.value)next.set(camera.camera_id,last.has(camera.camera_id)&&now-last.get(camera.camera_id)!<1500?30:0);fps.value=next},1000)})
onBeforeUnmount(()=>{generation++;if(timer)window.clearTimeout(timer);socket?.close();closeDecoders()})
</script>
<template><div class="camera-page"><header class="camera-page-head"><div><span class="eyebrow">SOURCE MONITOR</span><h2>Camera streams</h2><p>{{ fatalError || (cameras.length ? `${cameras.length} configured view${cameras.length===1?'':'s'} from the active capture rig.` : 'No cameras configured.') }}</p></div><button class="stream-button" @click="toggle">{{ playing ? 'Ⅱ  PAUSE ALL STREAMS' : '▶  PLAY ALL STREAMS' }}</button></header><div v-if="cameras.length" class="camera-grid-large"><article v-for="camera in cameras" :key="camera.camera_id" class="camera-large"><div class="camera-feed"><canvas :ref="(element)=>setCanvas(camera.camera_id,element)" :width="camera.width" :height="camera.height"/><span class="feed-label">CAM_{{String(camera.camera_id).padStart(2,'0')}}</span><span class="feed-live"><i/>{{playing?'LIVE':'PAUSED'}}</span><span class="feed-time">{{camera.width}} × {{camera.height}} · {{fps.get(camera.camera_id)||0}} FPS</span></div><div class="camera-info"><strong>CAMERA {{String(camera.camera_id).padStart(2,'0')}}</strong><span>{{camera.fps.toFixed(1)}} FPS · {{camera.width}} × {{camera.height}}</span></div></article></div><div v-else class="empty-state">Configure at least one capture camera to start previewing streams.</div></div></template>
<style scoped>.camera-page{width:100%;min-width:0;min-height:0;flex:1;padding:28px 30px 36px;overflow:hidden auto;color:#d5e0e2}.camera-page-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding-bottom:24px;border-bottom:1px solid #1e292d}.eyebrow{color:#70e3e0;font-size:9px;letter-spacing:.14em}h2{margin:8px 0;font-size:24px;font-weight:400}p{margin:0;color:#718087}.stream-button{padding:9px 12px;border:1px solid #24545a;border-radius:3px;background:#132528;color:#70e3e0;font-size:9px;letter-spacing:.08em}.camera-grid-large{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:22px}.camera-large{overflow:hidden;border:1px solid #1e292d;background:#10181b}.camera-feed{position:relative;display:grid;place-items:center;aspect-ratio:16/9;overflow:hidden;background:#0b1518}.camera-feed canvas{width:100%;height:100%;object-fit:cover}.feed-label,.feed-live,.feed-time{position:absolute;z-index:1;font-size:9px}.feed-label{top:12px;left:12px}.feed-live{top:12px;right:12px;color:#79dbb0}.feed-live i{width:6px;height:6px;display:inline-block;margin-right:5px;border-radius:50%;background:currentColor}.feed-time{bottom:12px;left:12px;color:#9eb3b4}.camera-info{display:flex;gap:14px;padding:13px;font-size:9px}.camera-info span{color:#718087}.empty-state{margin-top:22px;padding:40px 20px;border:1px dashed #2a3b3f;color:#718087;text-align:center}@media(max-width:900px){.camera-grid-large{grid-template-columns:1fr}}</style>
