<script setup lang="ts">
const metrics = [
  { label: 'CAPTURE RATE', value: '59.8', unit: 'FPS', detail: '4 synchronized sources', width: '96%', tone: 'green' },
  { label: 'INFERENCE LATENCY', value: '16.2', unit: 'MS', detail: 'RTMO-S pose pipeline', width: '72%', tone: 'cyan' },
  { label: 'TRIANGULATION', value: '98.4', unit: '%', detail: 'Mean confidence across joints', width: '98%', tone: 'green' },
  { label: 'GPU MEMORY', value: '4.2', unit: '/ 8 GB', detail: 'CUDA device 0 · 38°C', width: '52%', tone: 'orange' },
]
</script>
<template>
  <div class="metrics-page">
    <div class="metrics-hero"><div><span class="eyebrow">PIPELINE TELEMETRY</span><h2>Runtime performance</h2><p>Live health and throughput for the current capture session.</p></div><span class="healthy">HEALTHY</span></div>
    <div class="metrics-cards"><article v-for="metric in metrics" :key="metric.label" class="metric-card"><span class="metric-label">{{ metric.label }}</span><strong>{{ metric.value }} <small>{{ metric.unit }}</small></strong><span class="metric-detail">{{ metric.detail }}</span><div class="large-meter"><i :class="metric.tone" :style="{ width: metric.width }"></i></div></article></div>
    <div class="metric-lower"><section class="chart-card"><div class="card-title">FRAME TIME <span>LAST 30 SECONDS</span></div><div class="bars"><i v-for="n in 30" :key="n" :style="{ height: `${24 + ((n * 17) % 48)}%` }"></i></div><div class="chart-axis"><span>16.8 ms</span><span>14.2 ms</span><span>12.0 ms</span></div></section><section class="events-card"><div class="card-title">RECENT EVENTS <span>LIVE</span></div><div v-for="event in ['Frame sync restored','GPU memory pool allocated','Camera 04 exposure adjusted','Pose model warmed']" :key="event" class="event"><i></i><span>{{ event }}</span><time>10:42:08</time></div></section></div>
  </div>
</template>
<style scoped>
.metrics-page,.camera-page{padding:28px 30px;overflow:auto;height:100%;color:#d5e0e2}.metrics-hero,.camera-page-head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid #1e292d;padding-bottom:24px}.eyebrow,.card-title{font-size:9px;letter-spacing:.14em;color:#70e3e0}.metrics-hero h2,.camera-page h2{font-size:24px;font-weight:400;margin:8px 0}.metrics-hero p,.camera-page p{color:#718087}.healthy{color:#79dbb0;border:1px solid #285a4d;padding:5px 8px;border-radius:3px;font-size:9px}.metrics-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.metric-card,.chart-card,.events-card{background:#10181b;border:1px solid #1e292d;padding:18px}.metric-label{display:block;color:#718087;font-size:9px;letter-spacing:.1em}.metric-card strong{display:block;font-size:25px;font-weight:400;margin:16px 0 5px}.metric-card small{font-size:10px;color:#70e3e0}.metric-detail{color:#718087;font-size:9px}.large-meter{height:4px;background:#1c292d;margin-top:20px}.large-meter i{display:block;height:100%;background:#70e3e0}.large-meter i.green{background:#79dbb0}.large-meter i.orange{background:#d9925f}.metric-lower{display:grid;grid-template-columns:1.4fr 1fr;gap:12px}.card-title{display:flex;justify-content:space-between;margin-bottom:18px}.card-title span{color:#718087;font-size:8px}.bars{height:180px;display:flex;align-items:end;gap:5px;border-bottom:1px solid #26373b}.bars i{flex:1;background:#3f999e;min-height:12px}.chart-axis{display:flex;justify-content:space-between;color:#718087;font-size:9px;margin-top:8px}.event{display:flex;gap:10px;padding:13px 0;border-bottom:1px solid #1e292d;color:#a9b8b9}.event i{width:6px;height:6px;background:#79dbb0;border-radius:50%;margin-top:4px}.event time{margin-left:auto;color:#526368;font-size:9px}.camera-page{padding:28px 30px}.camera-grid-large{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:22px}.camera-large{background:#10181b;border:1px solid #1e292d}.camera-feed{height:260px;background:radial-gradient(ellipse,#245058,#0b1518);position:relative;display:grid;place-items:center;overflow:hidden}.camera-feed:after{content:'';position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 9px,#8be7e422 10px 11px)}.feed-placeholder{font-size:80px;color:#5fd4d2;opacity:.65}.feed-label,.feed-live,.feed-time{position:absolute;z-index:1;font-size:9px}.feed-label{left:12px;top:12px}.feed-live{right:12px;top:12px;color:#79dbb0}.feed-live i{display:inline-block;width:6px;height:6px;background:#79dbb0;border-radius:50%;margin-right:5px}.feed-time{left:12px;bottom:12px;color:#9eb3b4}.camera-info{display:flex;gap:14px;align-items:center;padding:13px;font-size:9px}.camera-info span{color:#718087}.camera-ok{color:#79dbb0!important;margin-left:auto}@media(max-width:900px){.metrics-cards{grid-template-columns:1fr 1fr}.metric-lower{grid-template-columns:1fr}}@media(max-width:650px){.camera-grid-large{grid-template-columns:1fr}}
 .metrics-page{overflow-y:auto;min-height:0}
</style>
