<script setup lang="ts">
import { ref } from 'vue'
import type { MetricsSnapshot, RuntimeStatus } from '../types/iris'
const props = defineProps<{ status: RuntimeStatus; metrics: MetricsSnapshot | null; logs: string[][] }>()
const api = window.api
const busy = ref(''), message = ref(''), metricPrefix = ref('')
const camera = ref({ camera_id: 1, device_index: 1, device_symbolic_link: '', width: 1920, height: 1080, frame_rate: 30, format: 'mjpeg', cuda_device: 0, sample_queue_capacity: 1, frame_pool_capacity: 4, overflow: 'drop-oldest', rotation: 'none', allow_format_fallback: false, reconnect: true })
const pose = ref({ backend: 'off', model_path: '@assets/pear_ehm_libtorch.pt', engine_path: '@assets/rtmo_s.engine', calibration_path: '' })
const recording = ref({ destination: 'recordings/iris-recording.mp4', bitrate: 8000000, frame_rate: 30 })
const shm = ref({ enabled: false, destination: 'Local\\IRIS_V2_Output', capacity_bytes: 67108864, legacy_v1: true })
const preview = ref({ http_enabled: true, mjpeg_enabled: true, h264_enabled: true, bind_address: '127.0.0.1', port: 8080, max_fps: 30, max_width: 1280, jpeg_quality: 75, bitrate: 4000000, queue_capacity: 16 })
const sync = ref({ tolerance_ms: 3, queue_capacity: 4, incomplete_batch_policy: 'drop' })
const calibration = ref({ output_path: 'rig-calibration.json' })
const edits = ref<Record<number, { width: number; height: number; frame_rate: number; rotation: string }>>({})
function edit(id: number, width: number, height: number, fps: number) { return edits.value[id] ?? (edits.value[id] = { width, height, frame_rate: fps || 30, rotation: 'none' }) }
async function call(name: string, action: () => Promise<unknown>): Promise<void> { busy.value = name; message.value = ''; try { await action(); message.value = 'Applied' } catch (error) { message.value = String(error) } finally { busy.value = '' } }
function addCamera() { const body = { ...camera.value }; return call('camera', () => api.addCamera(body)) }
function updateCamera(id: number) { return call('camera', () => api.configureCamera(id, { ...edit(id, 0, 0, 30) })) }
</script>
<template>
  <div class="runtime-controls">
    <details open><summary>RUNTIME <span>{{ props.status.pipeline || 'unknown' }}</span></summary><div class="control-fields"><small>STATE: {{ props.status.pipeline || 'unknown' }}</small><button @click="call('runtime', api.startPipeline)">START PIPELINE</button><button @click="call('runtime', api.stopPipeline)">STOP PIPELINE</button><button @click="call('runtime', api.shutdownRuntime)">SHUTDOWN</button></div></details>
    <details><summary>CAMERAS <span>{{ props.status.cameras?.length || 0 }}</span></summary><div class="control-fields"><input v-model.number="camera.camera_id" type="number" placeholder="Camera ID"/><input v-model.number="camera.device_index" type="number" placeholder="Device index"/><input v-model="camera.device_symbolic_link" placeholder="Device symbolic link"/><input v-model.number="camera.width" type="number" placeholder="Width"/><input v-model.number="camera.height" type="number" placeholder="Height"/><input v-model.number="camera.frame_rate" type="number" placeholder="FPS"/><select v-model="camera.format"><option>mjpeg</option><option>yuy2</option><option>bgra8</option></select><input v-model.number="camera.cuda_device" type="number" placeholder="CUDA device"/><input v-model.number="camera.sample_queue_capacity" type="number" placeholder="Sample queue"/><input v-model.number="camera.frame_pool_capacity" type="number" placeholder="Frame pool"/><select v-model="camera.overflow"><option>block</option><option>drop-oldest</option><option>drop-newest</option></select><select v-model="camera.rotation"><option>none</option><option>cw90</option><option>180</option><option>ccw90</option></select><label><input v-model="camera.allow_format_fallback" type="checkbox"/> format fallback</label><label><input v-model="camera.reconnect" type="checkbox"/> reconnect</label><button @click="addCamera">ADD CAMERA</button><div v-for="item in props.status.cameras || []" :key="item.camera_id" class="camera-row"><span>CAM {{ item.camera_id }}</span><button @click="call('camera', () => api.removeCamera(item.camera_id))">REMOVE</button><button @click="updateCamera(item.camera_id)">UPDATE</button></div></div></details>
    <details><summary>POSE</summary><div class="control-fields"><select v-model="pose.backend"><option value="off">off</option><option value="monocular">monocular</option><option value="2d">2D</option><option value="multiview">multiview</option></select><input v-model="pose.model_path" placeholder="Model path"/><input v-model="pose.engine_path" placeholder="Engine path"/><input v-model="pose.calibration_path" placeholder="Calibration path"/><button @click="call('pose', () => api.configurePose({ ...pose }))">APPLY POSE</button></div></details>
    <details><summary>RIG CALIBRATION</summary><div class="control-fields"><input v-model="calibration.output_path" placeholder="Output path"/><button @click="call('calibration', () => api.startCalibration({ ...calibration }))">START</button><button @click="call('calibration', api.cancelCalibration)">CANCEL</button><button @click="call('calibration', api.clearCalibration)">CLEAR</button><button @click="call('calibration', api.getCalibration)">REFRESH STATUS</button></div></details>
    <details><summary>RECORDING</summary><div class="control-fields"><input v-model="recording.destination" placeholder="Destination"/><input v-model.number="recording.bitrate" type="number" placeholder="Bitrate"/><input v-model.number="recording.frame_rate" type="number" placeholder="FPS"/><button @click="call('recording', () => api.startRecording({ ...recording }))">START</button><button @click="call('recording', api.stopRecording)">STOP</button></div></details>
    <details><summary>SHARED MEMORY</summary><div class="control-fields"><label><input v-model="shm.enabled" type="checkbox"/> enabled</label><input v-model="shm.destination" placeholder="Destination"/><input v-model.number="shm.capacity_bytes" type="number" placeholder="Capacity bytes"/><label><input v-model="shm.legacy_v1" type="checkbox"/> legacy v1</label><button @click="call('shared-memory', () => api.request('/outputs/shared-memory', 'PATCH', { ...shm }))">APPLY</button></div></details>
    <details><summary>PREVIEW</summary><div class="control-fields"><label><input v-model="preview.http_enabled" type="checkbox"/> HTTP</label><label><input v-model="preview.mjpeg_enabled" type="checkbox"/> MJPEG</label><label><input v-model="preview.h264_enabled" type="checkbox"/> H.264</label><input v-model="preview.bind_address" placeholder="Bind address"/><input v-model.number="preview.port" type="number" placeholder="Port"/><input v-model.number="preview.max_fps" type="number" placeholder="Max FPS"/><input v-model.number="preview.max_width" type="number" placeholder="Max width"/><input v-model.number="preview.jpeg_quality" type="number" placeholder="JPEG quality"/><input v-model.number="preview.bitrate" type="number" placeholder="H.264 bitrate"/><input v-model.number="preview.queue_capacity" type="number" placeholder="Queue capacity"/><button @click="call('preview', () => api.request('/outputs/preview', 'PATCH', { ...preview }))">APPLY</button></div></details>
    <details><summary>SYNCHRONIZER</summary><div class="control-fields"><input v-model.number="sync.tolerance_ms" type="number" placeholder="Tolerance ms"/><input v-model.number="sync.queue_capacity" type="number" placeholder="Queue capacity"/><select v-model="sync.incomplete_batch_policy"><option value="drop">drop</option><option value="partial">partial</option></select><button @click="call('synchronizer', () => api.request('/synchronizer', 'PATCH', { ...sync }))">APPLY</button></div></details>
    <details><summary>METRICS</summary><div class="control-fields"><input v-model="metricPrefix" placeholder="Metric prefix"/><button @click="call('metrics', api.getMetrics)">REFRESH</button><small>{{ Object.keys(props.metrics?.counters || {}).length }} counters · {{ Object.keys(props.metrics?.gauges || {}).length }} gauges</small></div></details>
    <details><summary>LOGS <span>{{ props.logs.length }}</span></summary><div class="control-log"><div v-for="(log, index) in props.logs" :key="index">{{ log.join(' · ') }}</div></div></details>
    <small v-if="message" class="control-message">{{ message }}</small>
  </div>
</template>
