<script setup lang="ts">
import { ref, watch } from 'vue'
import type { CalibrationSnapshot, CreateCameraRequest, MetricsSnapshot, RuntimeStatus } from '../types/iris'
import CameraManager from './CameraManager.vue'
const props = defineProps<{ status: RuntimeStatus; metrics: MetricsSnapshot | null; logs: string[][] }>()
const emit = defineEmits<{ (event: 'calibration-refresh', value: CalibrationSnapshot | null): void }>()
const api = window.api
const busy = ref(''), message = ref('')
const selectedCamera = ref<number | null>(null)
const metricPrefix = ref('')
const camera = ref<CreateCameraRequest>({ camera_id: 1, device_index: 1, device_symbolic_link: '', width: 1920, height: 1080, frame_rate: 30, format: 'mjpeg', cuda_device: 0, sample_queue_capacity: 1, frame_pool_capacity: 4, overflow: 'drop-oldest', rotation: 'none', allow_format_fallback: false, reconnect: true })
const pose = ref({ backend: 'off', model_path: '@assets/pear_ehm_libtorch.pt', engine_path: '@assets/rtmo_s.engine', calibration_path: '' })
const recording = ref({ destination: 'recordings/iris-recording.mp4', bitrate: 8000000, frame_rate: 30 })
const calibration = ref({ output_path: 'rig-calibration.json' })
const sync = ref({ tolerance_ms: 20, queue_capacity: 4, incomplete_batch_policy: 'drop' })
const shm = ref({ enabled: false, destination: 'Local\\IRIS_V2_Output', capacity_bytes: 67108864, legacy_v1: true })
const preview = ref({ http_enabled: true, mjpeg_enabled: true, h264_enabled: true, bind_address: '127.0.0.1', port: 8080, max_fps: 30, max_width: 1280, jpeg_quality: 75, bitrate: 4000000, queue_capacity: 16 })
async function call(name: string, action: () => Promise<unknown>) { busy.value = name; message.value = ''; try { await action(); message.value = 'Applied' } catch (error) { message.value = String(error) } finally { busy.value = '' } }
function post(path: string, body?: unknown) { return () => api.request(path, 'PATCH', body) }
watch(selectedCamera, (id) => { const item = props.status.cameras?.find((entry) => entry.camera_id === id); if (item) Object.assign(camera.value, { camera_id: item.camera_id, device_index: item.device_index ?? camera.value.device_index, device_symbolic_link: item.device_symbolic_link ?? '', width: item.width, height: item.height, frame_rate: typeof item.frame_rate === 'number' ? item.frame_rate : item.frame_rate?.value ?? item.fps, format: item.format ?? camera.value.format, cuda_device: item.cuda_device ?? camera.value.cuda_device, sample_queue_capacity: item.sample_queue_capacity ?? camera.value.sample_queue_capacity, frame_pool_capacity: item.frame_pool_capacity ?? camera.value.frame_pool_capacity, overflow: item.overflow ?? camera.value.overflow, rotation: item.rotation ?? camera.value.rotation, allow_format_fallback: item.allow_format_fallback ?? camera.value.allow_format_fallback, reconnect: item.reconnect ?? camera.value.reconnect }) })
async function updateCamera(): Promise<void> { if (selectedCamera.value === null) return; await call('camera', () => api.configureCamera(selectedCamera.value as number, { device_index: camera.value.device_index, device_symbolic_link: camera.value.device_symbolic_link, width: camera.value.width, height: camera.value.height, frame_rate: camera.value.frame_rate, format: camera.value.format, cuda_device: camera.value.cuda_device, sample_queue_capacity: camera.value.sample_queue_capacity, frame_pool_capacity: camera.value.frame_pool_capacity, overflow: camera.value.overflow, rotation: camera.value.rotation, allow_format_fallback: camera.value.allow_format_fallback, reconnect: camera.value.reconnect })) }
async function shutdown(): Promise<void> { if (window.confirm('Shutdown the IRIS runtime?')) await call('runtime', api.shutdownRuntime) }
async function clearCalibration(): Promise<void> { if (window.confirm('Clear the current rig calibration?')) await call('calibration', api.clearCalibration) }
async function refreshCalibration(): Promise<void> {
  await call('calibration', async () => {
    const response = await api.getCalibration() as { calibration?: CalibrationSnapshot | null }
    emit('calibration-refresh', response.calibration ?? null)
  })
}
</script>
<template>
  <div class="runtime-controls">
    <CameraManager :status="props.status" />
    <details open><summary>RUNTIME <span>{{ props.status.state || 'Unknown' }}</span></summary><div class="control-fields"><small>STATUS: {{ props.status.state || 'Unknown' }}<span v-if="props.status.last_error"> · {{ props.status.last_error }}</span></small><button class="primary-action" :disabled="!!busy" @click="call('runtime', api.startPipeline)">START PIPELINE</button><button :disabled="!!busy" @click="call('runtime', api.stopPipeline)">STOP PIPELINE</button><button :disabled="!!busy" @click="call('runtime', api.getStatus)">REFRESH STATUS</button><button class="danger-action" :disabled="!!busy" @click="shutdown">SHUTDOWN</button></div></details>
    <div class="control-group-title">SETUP</div>
    <details><summary>CAMERAS <span>{{ props.status.cameras?.length || 0 }} configured</span></summary><div class="control-fields"><select v-model="selectedCamera" aria-label="Camera to update"><option :value="null">New camera</option><option v-for="item in props.status.cameras || []" :key="item.camera_id" :value="item.camera_id">Camera {{ item.camera_id }}</option></select><input v-model.number="camera.camera_id" type="number" aria-label="Camera ID" placeholder="Camera ID"/><input v-model.number="camera.device_index" type="number" aria-label="Device index" placeholder="Device index"/><input v-model="camera.device_symbolic_link" aria-label="Device symbolic link" placeholder="Device symbolic link"/><input v-model.number="camera.width" type="number" aria-label="Width" placeholder="Width"/><input v-model.number="camera.height" type="number" aria-label="Height" placeholder="Height"/><input v-model.number="camera.frame_rate" type="number" aria-label="Frame rate" placeholder="FPS"/><select v-model="camera.format" aria-label="Pixel format"><option>mjpeg</option><option>yuy2</option><option>bgra8</option></select><input v-model.number="camera.cuda_device" type="number" aria-label="CUDA device" placeholder="CUDA device"/><input v-model.number="camera.sample_queue_capacity" type="number" aria-label="Sample queue capacity" placeholder="Sample queue"/><input v-model.number="camera.frame_pool_capacity" type="number" aria-label="Frame pool capacity" placeholder="Frame pool"/><select v-model="camera.overflow" aria-label="Overflow policy"><option>block</option><option>drop-oldest</option><option>drop-newest</option></select><select v-model="camera.rotation" aria-label="Camera rotation"><option>none</option><option>cw90</option><option>180</option><option>ccw90</option></select><label><input v-model="camera.allow_format_fallback" type="checkbox"/> Allow format fallback</label><label><input v-model="camera.reconnect" type="checkbox"/> Reconnect automatically</label><button :disabled="!!busy || selectedCamera !== null" @click="call('camera', () => api.addCamera({ ...camera }))">ADD CAMERA</button><button :disabled="!!busy || selectedCamera === null" @click="updateCamera">UPDATE CAMERA</button><div v-for="item in props.status.cameras || []" :key="item.camera_id" class="camera-row"><span>CAM {{ item.camera_id }}</span><button :disabled="!!busy" @click="call('camera', () => api.removeCamera(item.camera_id))">REMOVE</button></div></div></details>
    <details><summary>POSE <span>{{ props.status.pose_backend || 'Off' }}</span></summary><div class="control-fields"><select v-model="pose.backend" aria-label="Pose backend"><option value="off">Off</option><option value="monocular">Monocular</option><option value="2d">2D</option><option value="multiview">Multiview</option></select><input v-model="pose.model_path" aria-label="Model path" placeholder="Model path"/><input v-model="pose.engine_path" aria-label="Engine path" placeholder="Engine path"/><input v-model="pose.calibration_path" aria-label="Calibration path" placeholder="Calibration path"/><button :disabled="!!busy" @click="call('pose', () => api.configurePose({ ...pose }))">APPLY POSE</button></div></details>
    <details><summary>RIG CALIBRATION <span>{{ props.status.calibration ? 'Ready' : 'Required' }}</span></summary><div class="control-fields"><small v-if="props.status.calibration_tool">{{ props.status.calibration_tool.state }}<span v-if="props.status.calibration_tool.message"> · {{ props.status.calibration_tool.message }}</span></small><input v-model="calibration.output_path" aria-label="Calibration output path" placeholder="Output path"/><button :disabled="!!busy" @click="call('calibration', () => api.startCalibration({ ...calibration }))">START CALIBRATION</button><button :disabled="!!busy" @click="call('calibration', api.cancelCalibration)">CANCEL</button><button class="danger-action" :disabled="!!busy" @click="clearCalibration">CLEAR</button><button :disabled="!!busy" @click="refreshCalibration">REFRESH CALIBRATION</button></div></details>
    <div class="control-group-title">RUN</div>
    <details><summary>RECORDING <span>{{ props.status.recording ? 'Active' : 'Inactive' }}</span></summary><div class="control-fields"><input v-model="recording.destination" aria-label="Recording destination" placeholder="Destination"/><input v-model.number="recording.bitrate" type="number" aria-label="Recording bitrate" placeholder="Bitrate"/><input v-model.number="recording.frame_rate" type="number" aria-label="Recording frame rate" placeholder="FPS"/><button :disabled="!!busy" @click="call('recording', () => api.startRecording({ ...recording }))">START RECORDING</button><button :disabled="!!busy" @click="call('recording', api.stopRecording)">STOP RECORDING</button></div></details>
    <div class="control-group-title">OUTPUTS</div>
    <details><summary>PREVIEW <span>{{ props.status.preview?.connected_clients || 0 }} clients</span></summary><div class="control-fields"><label><input v-model="preview.http_enabled" type="checkbox"/> HTTP</label><label><input v-model="preview.mjpeg_enabled" type="checkbox"/> MJPEG</label><label><input v-model="preview.h264_enabled" type="checkbox"/> H.264</label><input v-model="preview.bind_address" aria-label="Preview bind address" placeholder="Bind address"/><input v-model.number="preview.port" type="number" aria-label="Preview port" placeholder="Port"/><input v-model.number="preview.max_fps" type="number" aria-label="Preview maximum FPS" placeholder="Max FPS"/><input v-model.number="preview.max_width" type="number" aria-label="Preview maximum width" placeholder="Max width"/><input v-model.number="preview.jpeg_quality" type="number" aria-label="JPEG quality" placeholder="JPEG quality"/><input v-model.number="preview.bitrate" type="number" aria-label="H264 bitrate" placeholder="H.264 bitrate"/><input v-model.number="preview.queue_capacity" type="number" aria-label="Preview queue capacity" placeholder="Queue capacity"/><button :disabled="!!busy" @click="call('preview', post('/outputs/preview', { ...preview }))">APPLY PREVIEW</button></div></details>
    <details><summary>SHARED MEMORY <span>{{ props.status.shared_memory_enabled ? 'Enabled' : 'Disabled' }}</span></summary><div class="control-fields"><label><input v-model="shm.enabled" type="checkbox"/> Enabled</label><input v-model="shm.destination" aria-label="Shared memory destination" placeholder="Destination"/><input v-model.number="shm.capacity_bytes" type="number" aria-label="Shared memory capacity" placeholder="Capacity bytes"/><label><input v-model="shm.legacy_v1" type="checkbox"/> Publish legacy v1</label><button :disabled="!!busy" @click="call('shared-memory', post('/outputs/shared-memory', { ...shm }))">APPLY SHARED MEMORY</button></div></details>
    <div class="control-group-title">ADVANCED</div>
    <details><summary>SYNCHRONIZER <span>{{ props.status.sync_tolerance_ms ?? 20 }} ms</span></summary><div class="control-fields"><input v-model.number="sync.tolerance_ms" type="number" aria-label="Synchronizer tolerance" placeholder="Tolerance ms"/><input v-model.number="sync.queue_capacity" type="number" aria-label="Queue capacity" placeholder="Queue capacity"/><select v-model="sync.incomplete_batch_policy" aria-label="Incomplete batch policy"><option value="drop">Drop incomplete batches</option><option value="partial">Emit partial batches</option></select><button :disabled="!!busy" @click="call('synchronizer', post('/synchronizer', { ...sync }))">APPLY SYNCHRONIZER</button></div></details>
    <details><summary>METRICS</summary><div class="control-fields"><input v-model="metricPrefix" aria-label="Metric prefix" placeholder="Metric prefix"/><button :disabled="!!busy" @click="call('metrics', () => api.getMetrics(metricPrefix))">REFRESH METRICS</button><small>{{ Object.keys(props.metrics?.counters || {}).length }} counters · {{ Object.keys(props.metrics?.gauges || {}).length }} gauges</small></div></details>
    <details><summary>LOGS <span>{{ props.logs.length }}</span></summary><div class="control-log"><div v-for="(log, index) in props.logs" :key="index">{{ log.join(' · ') }}</div><small v-if="!props.logs.length">No runtime events yet.</small></div></details>
    <small v-if="message" class="control-message" role="status">{{ message }}</small>
  </div>
</template>
